version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Map host port 8000 to container port 80
    depends_on:
      - db  # Wait for the database to be ready before starting the API service

  db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
    environment:
      POSTGRES_DB: StudyBookDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
